spring:
  # session 配置
  session:
    store-type: redis
    # session 30 天过期
    timeout: 2592000
  application:
    name: wkr-ai-code-mother-backend
  profiles:
    active: dev
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mysql.host}:${mysql.port}/${mysql.database}
    username: ${mysql.username}
    password: ${mysql.password}
  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}
      password: ${redis.password}
      ttl: 3600
      database: 1
      username: default
server:
  port: 8123
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.wkr.aicode.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
# AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: ${deepseek.api-key}
      model-name: ${deepseek.model-name}
      log-requests: true
      log-responses: true
      max-tokens: 16384
      strict-json-schema: true
      response-format: json_object
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: ${deepseek.api-key}
      model-name: ${deepseek.model-name}
      max-tokens: 16384
      log-requests: true
      log-responses: true
minio:
  endpoint: ${minio.endpoint}
  access-key: ${minio.access-key}
  secret-key: ${minio.secret-key}
